apiVersion: v1
kind: Pod
metadata:
  name: backstage-env
  labels:
    app: env
  namespace: backstage
spec:
  serviceAccountName: backstage-sa
  containers:
    - name: backstage-env
      image: 'quay.io/marwan_attar_ibm/backstage-demo:v10'
      ports:
        - containerPort: 7007
          name: http
      envFrom:
        - secretRef:
            name: git-secret
        - secretRef:
            name: tekton-secret
        - secretRef:
            name: cluster-secrets

