kind: Service
apiVersion: v1
metadata:
  name: backstage
  namespace: backstage
spec:
  ports:
    - name: http
      protocol: TCP
      port: 7007
      targetPort: http
  type: LoadBalancer
  selector:
    app: backstage

